### ISSUE TITLE
Error after 'npm run blockit' and solved with add folder manually 

### ISSUE THREAD

**Issue by imamfirmansyah** [mudza09/blockit-starter#1]
```C:\xampp\htdocs\blockit-starter>npm run blockit

Blockit Builder v3.0.2 running on Node.js v14.15.5

    builder url:    http://localhost:3001
    preview url:    http://localhost:3000

[20:18:07] - Waiting for changes...
fs.js:1021
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir './src/hooks/sections'
    at Object.readdirSync (fs.js:1021:3)
    at k.hookSections (file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:6:1472)
    at te (file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:17:5689)
    at oe (file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:17:5759)
    at file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:17:5764
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './src/hooks/sections'
}
```

Error showing after follow the instructions, blockit builder cannot find `sections` folder.

After add manually sections folder inside hooks folder, another error appear.
```C:\xampp\htdocs\blockit-starter>npm run blockit

Blockit Builder v3.0.2 running on Node.js v14.15.5

    builder url:    http://localhost:3001
    preview url:    http://localhost:3000

[20:26:03] - Waiting for changes...
fs.js:1021
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir './src/hooks/sections/previews'
    at Object.readdirSync (fs.js:1021:3)
    at k.hookSections (file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:6:1551)
    at te (file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:17:5689)
    at oe (file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:17:5759)
    at file:///C:/xampp/htdocs/blockit-starter/node_modules/blockit-builder/blockit.js:17:5764
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './src/hooks/sections/previews'
}
```

and error disappear after add manually `previews` folder. We run again `npm run blockit` and everything work fine!

**Comment by mudza09** [comment]
Thanks for this information, this happens because git doesn't allow to just create an empty folder inside the repo. we will fix this issue in next update.
